import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import client from "../apollo-client";
import { GET_ALL_ANIMES } from "../graphql/queries";

export async function getStaticProps() {
  const { data, loading } = await client.query({
    query: GET_ALL_ANIMES,
    variables: {
      page: 1,
      perPage: 10,
      type: "MANGA",
      sort: "POPULARITY_DESC",
    },
  });

  return {
    props: {
      data: data.Page.media,
      loading,
    },
  };
}

export default function Home({ data, loading }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {data.map((item) => (
            <a key={item.id} className={styles.card}>
              <h2>
                {item.title.english} - {item.title.userPreferred}
              </h2>

              <Image
                src={item.coverImage.extraLarge}
                alt={item.title.english}
                width={"250px"}
                height={"250px"}
                objectFit={"cover"}
              />
            </a>
          ))}

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
