import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import client from "../apollo-client";
import { GET_ANIMES } from "../graphql/queries";

export async function getStaticProps() {
  const { data } = await client.query({
    query: GET_ANIMES,
    variables: {
      type: "ANIME",
      sort: "POPULARITY_DESC",
    },
  });

  return {
    props: {
      animes: data.Page.media,
    },
  };
}

export default function Home({ animes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <div className={styles.grid}>
          {animes.map((anime) => (
            <a key={anime.id} className={styles.card}>
              <h2>
                {anime.title.english} - {anime.title.userPreferred}
              </h2>

              <Image
                src={anime.coverImage.extraLarge}
                alt={anime.title.english}
                width={"250px"}
                height={"250px"}
                objectFit={"cover"}
              />
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
